version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: {{cookiecutter.database_name}}
      POSTGRES_USER: {{cookiecutter.database_user}}
      POSTGRES_PASSWORD: {{cookiecutter.database_password}}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
